### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by CaddyDz** [spatie/laravel-remote#1]
is it possible to support at least latest version of php 7.4?

https://github.com/spatie/laravel-remote/blob/add355f8becdad72e0ffc068bfa473c1a520e859/composer.json#L18

**Comment by freekmurze** [comment]
Feel free to fork the package if you need php 7.4 support

**Comment by giovanniciriello** [comment]
Here is my working fork for php < 8.0

https://github.com/giovanniciriello/laravel-remote

**Comment by vesper8** [comment]
@giovanniciriello thanks for making this! I'm using your fork.

Any chance you could merge the latest commits, in particular this one https://github.com/spatie/laravel-remote/commit/2e7c7cd1614576e5ecef22adf8a091a567b11a40 ?

Many thanks!
